
[common]
	#Whether players will be rewarded with a Paimon Medal when they first join the world. Default is true.
	spawnWithMedal = true
	#The interval of Paimon's speech. Default is 1200 ticks.
	#Range: > 0
	soundInterval = 1200

