
[transfer]
	#If true, print current recipe type in log.Default:false
	PrintRecipeType = false
	#If tag has this mod's item, use it first.
	ModPreference = []
	#example:{\"itemName\" : \"minecraft:apple\", \"nbt\": \"{}\"}
	ItemBlacklist = []
	#If true, the ingredient currently displayed by JEI will be transferred
	UseDisplayedIngredient = false
	#example:{\"itemName\" : \"minecraft:apple\", \"nbt\": \"{}\"}
	ListItemPreference = []

[crafting-help]
	#If true, Crafting Helper will match other items even they can't auto-crafting
	MatchOtherItems = true
	#If true, it will make all similar ingredient switch at the same time 
	AllowSynchronousSwitchIngredient = true

