
[maid]
	#The item that can temptation maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTemptationItem = "minecraft:cake"
	#The maximum number of maids the player own
	#Range: > 0
	OwnerMaxMaidNum = 2147483647
	#The item that can tamed maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTamedItem = "minecraft:cake"
	#The item that can NTR maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidNtrItem = "minecraft:structure_void"
	#The max range of maid home mode
	#Range: 3 ~ 64
	MaidHomeRange = 8
	#The entity that the maid will not hurt when in ranged attack
	MaidRangedAttackIgnore = []
	#Maid can switch models freely
	MaidChangeModel = true

[chair]
	#Chair can be destroyed by anyone
	ChairCanDestroyedByAnyone = true
	#Chair can switch models freely
	ChairChangeModel = true

[misc]
	#Give a soul spell item for player first join
	GiveSoulSpell = true
	#Shrine Lamp Effect Cost (Power Point/Per Hour)
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampEffectCost = 0.9
	#Maid fairy's spawn probability (zombie is 100, enderman is 10)
	#Range: > 0
	MaidFairySpawnProbability = 10
	#Loss power point after player death
	#Range: 0.0 ~ 5.0
	PlayerDeathLossPowerPoint = 1.0
	#Shrine Lamp Max Storage Power Point
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampMaxStorage = 100.0
	#Maid fairy's power point
	#Range: 0.0 ~ 5.0
	MaidFairyPowerPoint = 0.16
	#Shrine Lamp Max Range Of Absorb Power Point
	#Range: > 0
	ShrineLampMaxRange = 6

